### ISSUE TITLE
`useField` does not return initial value on first render

### ISSUE THREAD

**Issue by mattbasta** [teslamotors/informed#436]
**Describe the bug**
If you create a form that specifies `initialValues`, then create a field using `useField`, the initial invocation of `useField` returns a `fieldState` that has `fieldState.value === undefined`. If you set a breakpoint inside `useField`, it does have an `initialValue` variable that is populated with the specified initial value.

The issue seems to be that `register` and `initialize` are called on the form controller inside a `useEffect` body (`initialize` being the method that sets the initial value to the form state's values). This means that every field always needs to re-render at least once in order to have the correct initial value.

Previous versions of `informed` did not have this behavior.

**To Reproduce**

https://codesandbox.io/s/sleepy-sammet-zcsnpn?file=/src/App.js

<details>
<summary>Code:</summary>

```js
import * as React from "react";
import { Form, useField } from "informed";

export default function App() {
  return (
    <Form initialValues={{ foo: "12345" }}>
      <MyField />
    </Form>
  );
}

function MyField() {
  const { fieldState, fieldApi } = useField("foo");
  // On first render, `step` _should_ be `'completed'`
  const [step, setStep] = React.useState(() => {
    if (fieldState.value?.length === 5) {
      return "completed";
    } else {
      return "initial";
    }
  });

  return step === "initial" ? (
    <div>
      <p>Nothing has been set yet</p>
      <input
        type="text"
        onChange={(e) => {
          fieldApi.setValue(e.target.value);
          if (e.target.value.length === 5) {
            setStep("completed");
          }
        }}
      />
    </div>
  ) : (
    <div>Thanks for completing</div>
  );
}

```

</details>

In the example, it is expected that the form will show the "completed" state on load, but it does not because the field renders with an undefined value initially.

This is problematic for a few reasons:
- You can't set the initial value to, say, an empty string so that `fieldState.value` is the correct type (e.g., always a string). This forces you to build all fields to handle the undefined case, even if that's always discarded.
- Fields which collect information in multiple steps (e.g., like a wizard) require state which is separate from the form state. Integrating external components which are stateful means that it's painful or impossible to have them behave correctly without resorting to forcing re-renders with `key` or rendering `null` when the value is undefined.
- For sizable forms, this has a performance cost. _Every_ form field that uses `initialValues` pays this performance cost.

**Comment by joepuzzo** [comment]
I understand the issue but react does not have any good way to register a field only once before the first render. React 18 and the react team IMO fucked things up when adding the double render in strict mode. Per reacts docs registrations should occur in the useEffects. A field is not registered with the form ( and therefore does not exist ) until the useEffect gets called. I will really need to think hard on if a clean way to initialize the field before the useEffect.

**Comment by mattbasta** [comment]
You could pass the initial value to a third argument on useFieldState within useField. That could turn get passed to the getter method on FormController for field state and override the value on the initial field state if the field hasn't been registered or initialized yet.

That doesn't solve the double render issue, but it prevents the fields from being rendered with an invalid field state value.


Out of curiosity, why do fields need to be initialized if initial values are provided? It's like a hint that the field will be created/used. If you pre-initialized the field state when an initial value is provided (because that's what the initial value is, right?) then a lot of this work could be front-loaded.

Registering the field for updates is fine in useEffect, it's storing the state that's a problem: you're mutating a single shared state when a component mounts. The confusing part for me is why you need to write anything to the form state _on first render_ rather than when the form controller is created with the initial values.

**Comment by mertcanaltin** [comment]
Hello, I wanted to make a little comment on this :heart: @mattbasta  @joepuzzo 

To solve this problem, you can use the initialValues ​​prop to specify the initial values ​​of the form fields. This prop is given to a Form component and specifies the initial values ​​of the form fields. For example, in the following snippet, the initial value for a field named foo is "12345":
```js
<Form initialValues={{ foo: "12345" }}>
  <MyField />
</Form>
```

This sets the fieldState.value to "12345" for a component that uses the useField hook inside the MyField component. In this way, you can make the component work correctly according to its initial value.

If you are experiencing a performance issue due to skipping the initial values ​​of the form fields, you can avoid this by using the initialValues ​​prop only when necessary. This way, you can optimize performance by setting initial values ​​for only the form fields that are needed.

If you are having other issues due to skipping form fields' initial values, you may need to properly use the form fields' state and API to resolve these issues. For example, you can properly manage the field state and API to ensure that form fields work correctly based on their initial values.

**Comment by joepuzzo** [comment]
@mattbasta So this is actually a "fun" problem. I at one point asked myself "Why not just set values === initialValues" in formController?? makes logical sense right? Well its not that simple. There are many cases where you have complex forms that either

A: Dont load all fields in one step at the start

B: Use relevance and sometimes the initialValues have data that is not actually part of the form

Example: initialValues = { foo: 'bar', baz: 'taz' }

But the form actually only has one field { foo: 'bar' }

After lots of going back and forth I decided that the source of truth for a field "EXISTING" or not would be if it registered itself. If a field registers itself ( mounts ) then we know for sure it exists.

Unfortunatley the only tool in my react toolbox I can use for this is useEffect. 

I have complained countless times to the react team about this but they love their useEffect and double render in strict mode. 

Also one might then say "Why not use useState(() => registerHERE)" instead OR use `useLayoutEffect` well those have issues as well due to server side rendering and the double render in strict mode respectivly.

It really is quite and annoying mess. I REALLY REALLY WISH REACT WOULD JUST GIVE ME A `componentDidMount` hook or something..

**Comment by mattbasta** [comment]
The `componentDidMount` lifecycle method would have this same problem, since it runs after render. 😉 No matter what API react exposes, you're in the same pickle because you want to mutate shared state as a side effect of the component mounting/registering, but the only place that has truly happened is after the first render has completed.

From first principles, we can't trust render to be a safe time to write state, because things like SSR and suspense will break the behavior. So you only have two choices: write the state after (like it is now) or write the state earlier (like I mentioned, in the form controller setup). The former has the issues I've documented. I'm curious how the latter could be explored to avoid this problem.

I'm not contending that the field should "exist" or not based on whether it's set in initial values. E.g., you can still load the value into the form controller state when it's created, but filter the values that get exposed through the public interface (like the submit handler) based on whether there's a field registered at that time. So you wouldn't just be reading the state directly, you'd be filtering it instead.

You could filter the "unmounted" fields out when you fetch all the values, but also just allow specific requests to go through. If I call useFieldState for a field that's not mounted, you could just return the hidden, otherwise-filtered state.

**Comment by joepuzzo** [comment]
Hmm I specifically did not do anything fancy for this feature you are requesting.. Why cant you use `useFieldState` to determine weather or not to show if something has been said yet?  Also you can use `modified` which is part of the field state to know if its modified from the initial state.

**Comment by joepuzzo** [comment]
In summary I feel like your goal can be achieved without me having to re architect how the initial values work.

**Comment by mattbasta** [comment]
I don't see this as a feature, this is a bug. The field renders with an undefined value, which contradicts the notion of "initial" value (since the initial render doesn't have that value). The component then rerenders without an observable reason (i.e., the first render was useless work for reasons that aren't my code's fault). Nobody would intuit this behavior, and nobody benefits from it.

Moreover, this is how informed used to work in recent memory. Post-upgrade my code now has bugs that are incredibly difficult to find without exhaustively testing each field in each form.

I could use the field state to determine whether to render or not, but I shouldn't have to. Anyone using initial values is now going to see warnings about uncontrolled components (because they say `value={fieldState.value}` which goes from undefined to a string) unless they add an unnecessary `?? ''` or return null. It's also unattractive for performance reasons.

I very much empathize with your reason for making it work this way, but it's an incredibly rough edge with some substantial downsides.

**Comment by joepuzzo** [comment]
Its not that simple https://github.com/teslamotors/informed/blob/master/src/FormController.js#L847 

See here ^^ how many things occur when the initialize function is called. Especially see how we need to sometimes mask the input passed 

Example: `initialValue={25}` but we need the value shown to be `$25.00`

**Comment by joepuzzo** [comment]
I may have fix but need to do some testing stand by

**Comment by joepuzzo** [comment]
Ok try the latest version I moved a few lines around to get it to initialize earlier

**Comment by joepuzzo** [comment]
Im going to close this as it is fixed
